### ISSUE TITLE
Is it for `backend User` and `frontend User`?

### ISSUE THREAD

**Issue by typo3ua** [sourcebroker/restrictfe#15]
Hello!

Is it conditions only for `backend User`? 
Can I use them for `frontend User`?

Thanks!

**Comment by kszymukowicz** [comment]
It's only for backend user.

**Comment by typo3ua** [comment]
thank for reply... do you have plans to make it for frontend users?

**Comment by kszymukowicz** [comment]
No. Can you explain your use case?

**Comment by typo3ua** [comment]
thanks!

I need to associate each user their IP- address and if a user with their IP- address go to the site then they automatically get authorisation and access to all site... can you advise something?

**Comment by kszymukowicz** [comment]
try https://packagist.org/packages/aoe/aoe_ipauth

**Comment by typo3ua** [comment]
thanks! yes i saw it but i not sure that it is what i need ... yours extension better

**Comment by kszymukowicz** [comment]
I am not sure there is extension which will fit your needs. 
Mine is also not good because there is no mapping of user to IP (I mean for BE which is impemented).

**Comment by typo3ua** [comment]
OK! Thank you for the advice. Good luck!
